repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
-   repo: https://github.com/ambv/black
    # black: automatic code re-formatter
    rev: stable
    hooks:
    - id: black
      description: "Formatting code"
      language: python
      language_version: 3.8.5
-   repo: https://gitlab.com/pycqa/flake8
    # flake8: Style guide enforcer
    rev: 3.8.4
    hooks:
    - id: flake8
      description: "Styling guide enforcement"
      language: python
      language_version: 3.8.5
